{
 "title": "RED Method",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_MIMIR", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   { "name": "DS_TEMPO", "query": "tempo" }
  ]
 },
 "panels": [
  {
   "title": "Duration — P50 / P95 / P99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"bookinfo-productpage.*\"}[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"bookinfo-productpage.*\"}[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"bookinfo-productpage.*\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Errors Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"bookinfo-productpage.*\", code=~\"5.*|4.*\"}[5m])) \n/ \nsum(rate(traefik_service_requests_total{service=~\"bookinfo-productpage.*\"}[5m])) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "Rate — Throughput RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"bookinfo-productpage.*\"}[5m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error / Warning Logs — bookinfo",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"bookinfo\"} |~ `(?i)(error|exception|warn|5[0-9]{2})`"
    }
   ]
  },
  {
   "title": "Slow Traces — duration > 500ms",
   "type": "traces",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "{resource.service.name=~\"productpage.*|reviews.*\" && duration > 500ms}",
     "tableType": "traces",
     "limit": 20
    }
   ]
  }
 ]
}